name: "Cron #2"

on:
  schedule:
    - cron:  '10/1 * * * *'
  workflow_dispatch:


jobs:
  cron2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout 📡
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache node_modules 💰
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies 🧬
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Store Playwright's Version 🪪
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | tr '\n' ' ' |  sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version ⚰️
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup Playwright ⚙️
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Cron task 👀
        run: npm run jobs
        env:
          CI: false

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
